name: 'CD - Deploy Payment Processor to Azure Functions'

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: 'tc-fiap-payment-processor'
  PROJECT_PATH: 'PaymentProcessor.csproj'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build and Publish'
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration Release --output ./publish

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './publish'